<?php

namespace App\DataFixtures;

class CategoryDataFixtures
{
    public static function getData()
    {    
        $categoriesDatas = [
            'Abstrait',
            'Afrique',
            'Agriculture',
            'Alimentation',
            'Amérique',
            'Animaux',
            'Archéologie',
            'Arts',
            'Asie',
            'Aventure',
            'Bandes Dessinées',
            'Banquise',
            'Casino',
            'Cinéma',
            'Commerce',
            'Construction',
            'Contemporain',
            'Contes',
            'Cyberpunk',
            'De Cape et',
            'Dinosaures',
            'Economie',
            'Enigme',
            'Enquête',
            'Epoque moderne',
            'Espace',
            'Europe',
            'Exploration',
            'Fantastique',
            'Folklore',
            'Guerre',
            'Histoire',
            'Horreur',
            'Humour',
            'Industrie',
            'Littérature',
            'Loisirs',
            'Magie',
            'Médiéval',
            'Moyen Age',
            'Moyen-Orient',
            'Musique',
            'Mythologie',
            'Nature',
            'Navigation',
            'Océan',
            'Océanie',
            'Onirique',
            'Paris',
            'Pirates',
            'Polar',
            'Politique',
            'Post-Apocalypse',
            'Préhistoire',
            'Religion',
            'Renaissance',
            'Science Fiction',
            'Sciences',
            'Sports',
            'Steampunk',
            'Superhéros',
            'Train',
            'Transports',
            'Victorien',
            'Vie quotidienne',
            'Viking',
            'Western',
            'Zombies',
        ];
       
        return $categoriesDatas;
    }
}
