export default [
    {
        id: 1,
        name: "BlaBlaQuest",
        game: "Cascadia",
        date: "10/02/2022",
        city: "Roubaix",
        nbrOfPlayers: 2,
        nbrOfPlayersMax: 5,
        image: "src/assets/img/default.jpg",
    },
    {
        id: 2,
        name: "BlaBlaQuest",
        game: "Cascadia",
        date: "10/02/2022",
        city: "Wattrelos",
        nbrOfPlayers: 5,
        nbrOfPlayersMax: 5,
        image: "src/assets/img/default.jpg",
    },
    {
        id: 3,
        name: "BlaBlaQuest",
        game: "Cascadia",
        date: "10/02/2022",
        city: "Tourcoing",
        nbrOfPlayers: 4,
        nbrOfPlayersMax: 5,
        image: "src/assets/img/default.jpg",
    },
    {
        id: 4,
        name: "BlaBlaQuest",
        game: "Cascadia",
        date: "10/02/2022",
        city: "Lille",
        nbrOfPlayers: 3,
        nbrOfPlayersMax: 5,
        image: "src/assets/img/default.jpg",
    },
]